services:
  sql-server:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: simple_api_database_mock_container
    restart: always
    #required ACCEPT_EULA from docs
    environment:
      - ACCEPT_EULA=Y

      - MSSQL_SA_PASSWORD=Dochazka123 
    ports:
      # Host_Port : Container_Port
      - "1433:1433" 
    volumes:
      # data stored when container is shut down (iside docker root)
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: